version: '3'

services:
    db:
        container_name: db
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=db
        volumes:
            - db:/var/lib/postgresql/data
    app:
        container_name: app
        build: .
        volumes:
            - .:/app
        depends_on:
            - db

volumes:
    db:

networks:
    default:
        external:
            name: munchkin
