--Tipos

CREATE TYPE raca AS ENUM (
    'Humano', 'Elfo', 'Halfling', 'Anao'
);

CREATE TYPE classe AS ENUM (
    'Guerreiro', 'Mago', 'Ladrao', 'Clerigo'
);

CREATE TYPE tipo_equip AS ENUM (
    'Cabeca', 'Arma', 'Armadura', 'Pes'
);

CREATE TYPE tipo_porcao AS ENUM (
    'Vida', 'Confusao', 'Forca'
);

CREATE TYPE tipo_npc AS ENUM (
    'Vendedor', 'Passivo'
);


CREATE TABLE IF NOT EXISTS jogador (
    personagem_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    nome VARCHAR(20) NOT NULL,
    raca_personagem raca NOT NULL,
    classe_personagem classe DEFAULT NULL,
    nivel INTEGER NOT NULL DEFAULT 1,
    forca_combate INTEGER NOT NULL DEFAULT 0,
    cabeca INTEGER  DEFAULT NULL,
    arma INTEGER  DEFAULT NULL,
    armadura INTEGER  DEFAULT NULL,
    pes INTEGER  DEFAULT NULL,
    missao_id INTEGER  NOT NULL DEFAULT 0,
    sala_id INTEGER  NOT NULL DEFAULT 0,


    PRIMARY KEY (personagem_id)
    FOREIGN KEY (cabeca)
    FOREIGN KEY (arma)
    FOREIGN KEY (armadura)
    FOREIGN KEY (pes)
    FOREIGN KEY (missao_id)
    FOREIGN KEY (sala_id)
    
);


-- Mochila
CREATE TABLE IF NOT EXISTS mochila (
    mochila_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    capacidade INTEGER NOT NULL DEFAULT 10,
    total_itens INTEGER NOT NULL DEFAULT 0,
    personagem_id INTEGER NOT NULL DEFAULT 0,
    

    PRIMARY KEY (mochila_id)
    FOREIGN KEY (personagem_id)
);

CREATE TABLE IF NOT EXISTS item (

    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    nome VARCHAR(20) NOT NULL, 
    valor INTEGER NOT NULL DEFAULT 0, 
    bonus INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (item_id)

);

CREATE TABLE IF NOT EXISTS equipamento (

    equip_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    classe classe_personagem NOT NULL,
    tipo tipo_equip DEFAULT NULL,

    PRIMARY KEY (equipe_id),
    FOREIGN KEY (equip_id) REFERENCES [item] (item_id)

    
);

CREATE TABLE IF NOT EXISTS porcao (

    porcao_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    tipo tipo_porcao DEFAULT NULL,

    PRIMARY KEY (porcao_id),
    FOREIGN KEY (porcao_id) REFERENCES [item] (item_id)


);

CREATE TABLE IF NOT EXISTS inimigo (

    inimigo_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    nome VARCHAR(20) NOT NULL,
    nivel INTEGER NOT NULL DEFAULT 1,
    jogador_id INTEGER DEFAULT NULL,

    PRIMARY KEY (inimigo_id)
    FOREIGN KEY (jogador_id) REFERENCES [jogador] (personagem_id)

);


CREATE TABLE IF NOT EXISTS npc (

    personagem_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    nome VARCHAR(20) NOT NULL,
    raca_npc raca DEFAULT NULL,
    tipo tipo_npc DEFAULT(1),

    PRIMARY KEY(personagem_id)

);

CREATE TABLE IF NOT EXISTS sala (

    sala_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    descricao VARCHAR(100),
    nome VARCHAR(20),

    PRIMARY KEY (sala_id)

);

CREATE TABLE IF NOT EXISTS missao (

    missao_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    nome VARCHAR(20),
    descricao VARCHAR(100),
    

    PRIMARY KEY (missao_id)

);




